"""Fill a development instance with demo videos generated by ffmpeg.

Usage (from backend/):
    CONFIG_DIR=./.dev/config MEDIA_DIR=./.dev/media uv run python scripts/seed_demo.py

Useful when YouTube is not reachable, e.g. for UI work or screenshots.
"""

from __future__ import annotations

import random
import subprocess
import sys
from datetime import UTC, date, datetime, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.config import Settings
from app.db import make_engine, make_session_factory
from app.main import init_storage
from app.migrate import run_migrations
from app.models import (
    Channel,
    ItemState,
    Subscription,
    SubscriptionItem,
    SubscriptionKind,
    Subtitle,
    VideoStatus,
)
from app.services.catalog import channel_url
from app.services.downloader import VideoMetadata
from app.services.library import relative_to_media, video_base_path
from app.services.videos import upsert_video

CHANNELS = [
    ("UCdemo-nature", "Stille Natur", "@stillenatur"),
    ("UCdemo-tech", "Technik Einfach", "@technikeinfach"),
    ("UCdemo-kitchen", "Küche am Abend", "@kuecheamabend"),
]
TITLES = [
    "Ein Morgen am Bergsee in 4K",
    "Warum SSDs langsamer werden – und was hilft",
    "Pasta wie in Rom: Cacio e Pepe",
    "Nordlichter über Lappland",
    "Raspberry Pi als Mediaserver einrichten",
    "Sauerteig für Anfänger",
    "Regen im Wald – 1 Stunde Naturklang",
    "Die beste Tastatur für Programmierer?",
    "Gemüsecurry in 20 Minuten",
    "Wanderung zum Gletscher",
    "Heimnetz absichern: Die wichtigsten Schritte",
    "Tiramisu ohne Ei",
]
COLORS = ["0x1f6feb", "0x2ea043", "0xbf8700", "0x8250df", "0xcf222e", "0x0a84ff"]
CHANNEL_COLORS = {
    "UCdemo-nature": "0x2ea043",
    "UCdemo-tech": "0x0a84ff",
    "UCdemo-kitchen": "0xbf8700",
}


def ffmpeg(*args: str) -> None:
    subprocess.run(["ffmpeg", "-loglevel", "error", "-y", *args], check=True)  # noqa: S603, S607


def main() -> None:
    settings = Settings()
    init_storage(settings)
    engine = make_engine(settings.db_url)
    run_migrations(engine)
    sessions = make_session_factory(engine)
    random.seed(7)
    today = date.today()

    with sessions() as db:
        for index, title in enumerate(TITLES):
            channel_id, channel_name, handle = CHANNELS[index % len(CHANNELS)]
            youtube_id = f"demo{index:07d}"
            uploaded = today - timedelta(days=index * 9 + random.randint(0, 6))
            duration = 20
            meta = VideoMetadata(
                youtube_id=youtube_id,
                title=title,
                webpage_url=f"https://www.youtube.com/watch?v={youtube_id}",
                description=(
                    f"{title}.\n\nEin Demo-Video für TubeVault, erzeugt mit ffmpeg.\n"
                    "Mehr Infos: https://github.com/Lua-x/TubeVault"
                ),
                channel_id=channel_id,
                channel_name=channel_name,
                channel_handle=handle,
                upload_date=uploaded,
                duration_s=duration,
                view_count=random.randint(1_000, 2_000_000),
                chapters=[
                    {"start": 0.0, "end": 5.0, "title": "Einleitung"},
                    {"start": 5.0, "end": 12.0, "title": "Hauptteil"},
                    {"start": 12.0, "end": 20.0, "title": "Fazit"},
                ],
            )
            video = upsert_video(db, meta, None)
            assert video.channel is not None
            base = settings.media_dir / video_base_path(
                video.channel.folder_name, uploaded, title, youtube_id
            )
            base.parent.mkdir(parents=True, exist_ok=True)
            mp4 = base.parent / f"{base.name}.mp4"
            thumb = base.parent / f"{base.name}-thumb.jpg"
            vtt = base.parent / f"{base.name}.de.vtt"
            color = COLORS[index % len(COLORS)]
            if not mp4.exists():
                ffmpeg(
                    "-f",
                    "lavfi",
                    "-i",
                    f"gradients=s=1280x720:c0={color}:c1=0x101014:duration={duration}:speed=0.02",
                    "-f",
                    "lavfi",
                    "-i",
                    f"sine=frequency={220 + index * 40}:duration={duration}",
                    "-vf",
                    "format=yuv420p",
                    "-c:v",
                    "libx264",
                    "-preset",
                    "veryfast",
                    "-c:a",
                    "aac",
                    "-shortest",
                    "-movflags",
                    "+faststart",
                    str(mp4),
                )
            if not thumb.exists():
                ffmpeg("-ss", "2", "-i", str(mp4), "-frames:v", "1", "-q:v", "3", str(thumb))
            vtt.write_text(
                "WEBVTT\n\n00:00:01.000 --> 00:00:04.000\nWillkommen bei TubeVault.\n\n"
                "00:00:06.000 --> 00:00:10.000\nDas ist ein Demo-Untertitel.\n",
                encoding="utf-8",
            )
            video.file_path = relative_to_media(settings.media_dir, mp4)
            video.thumbnail_path = relative_to_media(settings.media_dir, thumb)
            video.filesize = mp4.stat().st_size
            video.width, video.height = 1280, 720
            video.vcodec, video.acodec = "avc1.64001f", "mp4a.40.2"
            video.status = VideoStatus.READY
            video.added_at = datetime.now(UTC) - timedelta(hours=index)
            video.downloaded_at = video.added_at
            video.subtitles.clear()
            db.flush()
            video.subtitles.append(
                Subtitle(
                    lang="de",
                    label="Deutsch",
                    is_auto=False,
                    file_path=relative_to_media(settings.media_dir, vtt),
                )
            )
            db.commit()
            print(f"✓ {title}")

        seed_subscriptions(db, settings.media_dir)


def seed_subscriptions(db, media_dir: Path) -> None:  # type: ignore[no-untyped-def]
    """One subscription per demo channel, with artwork and a few filtered entries."""
    now = datetime.now(UTC)
    for index, (channel_id, name, _handle) in enumerate(CHANNELS):
        channel = db.query(Channel).filter_by(youtube_id=channel_id).one()
        color = CHANNEL_COLORS[channel_id]
        folder = media_dir / channel.folder_name
        avatar, banner = folder / "folder.jpg", folder / "banner.jpg"
        ffmpeg("-f", "lavfi", "-i", f"gradients=s=400x400:c0={color}:c1=0x111114",
               "-frames:v", "1", str(avatar))  # fmt: skip
        ffmpeg("-f", "lavfi", "-i", f"gradients=s=1600x400:c0=0x111114:c1={color}",
               "-frames:v", "1", str(banner))  # fmt: skip
        channel.avatar_path = relative_to_media(media_dir, avatar)
        channel.banner_path = relative_to_media(media_dir, banner)

        sub = db.query(Subscription).filter_by(youtube_id=channel_id).one_or_none()
        if sub is None:
            sub = Subscription(
                kind=SubscriptionKind.CHANNEL,
                youtube_id=channel_id,
                url=channel_url(channel_id),
                title=name,
                channel_id=channel.id,
                check_interval_minutes=[360, 720, 1440][index],
                include_shorts=index == 1,
                keep_last=[None, 10, None][index],
                min_duration_s=[None, None, 180][index],
            )
            db.add(sub)
            db.flush()
        sub.last_checked_at = now - timedelta(minutes=40 + index * 25)
        sub.next_check_at = now + timedelta(hours=5 + index)
        db.query(SubscriptionItem).filter_by(subscription_id=sub.id).delete()
        for video in channel.videos:
            db.add(SubscriptionItem(
                subscription_id=sub.id, youtube_id=video.youtube_id, title=video.title,
                upload_date=video.upload_date, duration_s=video.duration_s,
                state=ItemState.DOWNLOADED, video_id=video.id,
            ))  # fmt: skip
        for n, (state, reason) in enumerate([
            (ItemState.FILTERED, "Shorts ausgeschlossen"),
            (ItemState.FILTERED, "Kürzer als 3 min"),
            (ItemState.SKIPPED, "Älter – beim Abonnieren übersprungen"),
        ]):  # fmt: skip
            db.add(SubscriptionItem(
                subscription_id=sub.id, youtube_id=f"{channel_id[-6:]}{n:05d}",
                title=f"{name}: älteres Video {n + 1}", state=state, reason=reason,
                upload_date=(now - timedelta(days=200 + n * 30)).date(), duration_s=95,
            ))  # fmt: skip
    db.commit()
    print("✓ Abos")


if __name__ == "__main__":
    main()
