"""Fill a development instance with demo videos generated by ffmpeg.

Usage (from backend/):
    CONFIG_DIR=./.dev/config MEDIA_DIR=./.dev/media uv run python scripts/seed_demo.py

Watch progress and playlists are created for the first admin, so sign in once (or set
ADMIN_USER/ADMIN_PASSWORD) before seeding to get them.

Useful when YouTube is not reachable, e.g. for UI work or screenshots.
"""

from __future__ import annotations

import random
import subprocess
import sys
from datetime import UTC, date, datetime, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.config import Settings
from app.db import make_engine, make_session_factory
from app.main import init_storage
from app.migrate import run_migrations
from app.models import (
    Channel,
    DownloadJob,
    ItemState,
    JobStatus,
    Playlist,
    PlaylistItem,
    SponsorSegment,
    Subscription,
    SubscriptionItem,
    SubscriptionKind,
    Subtitle,
    User,
    Video,
    VideoStatus,
    WatchProgress,
)
from app.services.app_settings import load_app_settings, save_app_settings
from app.services.catalog import channel_url
from app.services.downloader import VideoMetadata
from app.services.library import relative_to_media, video_base_path
from app.services.videos import upsert_video

CHANNELS = [
    ("UCdemo-nature", "Stille Natur", "@stillenatur"),
    ("UCdemo-tech", "Technik Einfach", "@technikeinfach"),
    ("UCdemo-kitchen", "Küche am Abend", "@kuecheamabend"),
]
TITLES = [
    "Ein Morgen am Bergsee in 4K",
    "Warum SSDs langsamer werden – und was hilft",
    "Pasta wie in Rom: Cacio e Pepe",
    "Nordlichter über Lappland",
    "Raspberry Pi als Mediaserver einrichten",
    "Sauerteig für Anfänger",
    "Regen im Wald – 1 Stunde Naturklang",
    "Die beste Tastatur für Programmierer?",
    "Gemüsecurry in 20 Minuten",
    "Wanderung zum Gletscher",
    "Heimnetz absichern: Die wichtigsten Schritte",
    "Tiramisu ohne Ei",
]
DURATIONS = [214, 286, 152, 175, 324, 248, 190, 301, 136, 312, 263, 118]
COLORS = ["0x1f6feb", "0x2ea043", "0xbf8700", "0x8250df", "0xcf222e", "0x0a84ff"]
CHANNEL_COLORS = {
    "UCdemo-nature": "0x2ea043",
    "UCdemo-tech": "0x0a84ff",
    "UCdemo-kitchen": "0xbf8700",
}


def ffmpeg(*args: str) -> None:
    subprocess.run(["ffmpeg", "-loglevel", "error", "-y", *args], check=True)  # noqa: S603, S607


def main() -> None:
    settings = Settings()
    init_storage(settings)
    engine = make_engine(settings.db_url)
    run_migrations(engine)
    sessions = make_session_factory(engine)
    random.seed(7)
    today = date.today()

    with sessions() as db:
        for index, title in enumerate(TITLES):
            channel_id, channel_name, handle = CHANNELS[index % len(CHANNELS)]
            youtube_id = f"demo{index:07d}"
            uploaded = today - timedelta(days=index * 9 + random.randint(0, 6))
            duration = DURATIONS[index]
            meta = VideoMetadata(
                youtube_id=youtube_id,
                title=title,
                webpage_url=f"https://www.youtube.com/watch?v={youtube_id}",
                description=(
                    f"{title}.\n\nEin Demo-Video für TubeVault, erzeugt mit ffmpeg.\n"
                    "Mehr Infos: https://github.com/Lua-x/TubeVault"
                ),
                channel_id=channel_id,
                channel_name=channel_name,
                channel_handle=handle,
                upload_date=uploaded,
                duration_s=duration,
                view_count=random.randint(1_000, 2_000_000),
                chapters=[
                    {"start": 0.0, "end": duration * 0.2, "title": "Einleitung"},
                    {"start": duration * 0.2, "end": duration * 0.65, "title": "Hauptteil"},
                    {"start": duration * 0.65, "end": float(duration), "title": "Fazit"},
                ],
            )
            video = upsert_video(db, meta, None)
            assert video.channel is not None
            base = settings.media_dir / video_base_path(
                video.channel.folder_name, uploaded, title, youtube_id
            )
            base.parent.mkdir(parents=True, exist_ok=True)
            mp4 = base.parent / f"{base.name}.mp4"
            thumb = base.parent / f"{base.name}-thumb.jpg"
            vtt = base.parent / f"{base.name}.de.vtt"
            color = COLORS[index % len(COLORS)]
            if not mp4.exists():
                ffmpeg(
                    "-f",
                    "lavfi",
                    "-i",
                    f"gradients=s=1280x720:r=10:c0={color}:c1=0x101014:duration={duration}"
                    ":speed=0.01",
                    "-f",
                    "lavfi",
                    "-i",
                    f"sine=frequency={220 + index * 40}:duration={duration}",
                    "-vf",
                    "format=yuv420p",
                    "-c:v",
                    "libx264",
                    "-preset",
                    "ultrafast",
                    "-c:a",
                    "aac",
                    "-shortest",
                    "-movflags",
                    "+faststart",
                    str(mp4),
                )
            if not thumb.exists():
                ffmpeg("-ss", "2", "-i", str(mp4), "-frames:v", "1", "-q:v", "3", str(thumb))
            vtt.write_text(
                "WEBVTT\n\n00:00:01.000 --> 00:00:04.000\nWillkommen bei TubeVault.\n\n"
                "00:00:06.000 --> 00:00:10.000\nDas ist ein Demo-Untertitel.\n",
                encoding="utf-8",
            )
            video.file_path = relative_to_media(settings.media_dir, mp4)
            video.thumbnail_path = relative_to_media(settings.media_dir, thumb)
            video.filesize = mp4.stat().st_size
            video.width, video.height = 1280, 720
            video.vcodec, video.acodec = "avc1.64001f", "mp4a.40.2"
            video.status = VideoStatus.READY
            video.added_at = datetime.now(UTC) - timedelta(hours=index)
            video.downloaded_at = video.added_at
            video.subtitles.clear()
            db.flush()
            video.subtitles.append(
                Subtitle(
                    lang="de",
                    label="Deutsch",
                    is_auto=False,
                    file_path=relative_to_media(settings.media_dir, vtt),
                )
            )
            db.commit()
            print(f"✓ {title}")

        seed_subscriptions(db, settings.media_dir)
        seed_library(db)


def seed_subscriptions(db, media_dir: Path) -> None:  # type: ignore[no-untyped-def]
    """One subscription per demo channel, with artwork and a few filtered entries."""
    now = datetime.now(UTC)
    for index, (channel_id, name, _handle) in enumerate(CHANNELS):
        channel = db.query(Channel).filter_by(youtube_id=channel_id).one()
        color = CHANNEL_COLORS[channel_id]
        folder = media_dir / channel.folder_name
        avatar, banner = folder / "folder.jpg", folder / "banner.jpg"
        ffmpeg("-f", "lavfi", "-i", f"gradients=s=400x400:c0={color}:c1=0x111114",
               "-frames:v", "1", str(avatar))  # fmt: skip
        ffmpeg("-f", "lavfi", "-i", f"gradients=s=1600x400:c0=0x111114:c1={color}",
               "-frames:v", "1", str(banner))  # fmt: skip
        channel.avatar_path = relative_to_media(media_dir, avatar)
        channel.banner_path = relative_to_media(media_dir, banner)

        sub = db.query(Subscription).filter_by(youtube_id=channel_id).one_or_none()
        if sub is None:
            sub = Subscription(
                kind=SubscriptionKind.CHANNEL,
                youtube_id=channel_id,
                url=channel_url(channel_id),
                title=name,
                channel_id=channel.id,
                check_interval_minutes=[360, 720, 1440][index],
                include_shorts=index == 1,
                keep_last=[None, 10, None][index],
                min_duration_s=[None, None, 180][index],
            )
            db.add(sub)
            db.flush()
        sub.last_checked_at = now - timedelta(minutes=40 + index * 25)
        sub.next_check_at = now + timedelta(hours=5 + index)
        db.query(SubscriptionItem).filter_by(subscription_id=sub.id).delete()
        for video in channel.videos:
            db.add(SubscriptionItem(
                subscription_id=sub.id, youtube_id=video.youtube_id, title=video.title,
                upload_date=video.upload_date, duration_s=video.duration_s,
                state=ItemState.DOWNLOADED, video_id=video.id,
            ))  # fmt: skip
        for n, (state, reason) in enumerate([
            (ItemState.FILTERED, "Shorts ausgeschlossen"),
            (ItemState.FILTERED, "Kürzer als 3 min"),
            (ItemState.SKIPPED, "Älter – beim Abonnieren übersprungen"),
        ]):  # fmt: skip
            db.add(SubscriptionItem(
                subscription_id=sub.id, youtube_id=f"{channel_id[-6:]}{n:05d}",
                title=f"{name}: älteres Video {n + 1}", state=state, reason=reason,
                upload_date=(now - timedelta(days=200 + n * 30)).date(), duration_s=95,
            ))  # fmt: skip
    db.commit()
    print("✓ Abos")


def seed_library(db) -> None:  # type: ignore[no-untyped-def]
    """Watch progress, two playlists and SponsorBlock segments for the first admin."""
    videos = db.query(Video).order_by(Video.youtube_id).all()
    now = datetime.now(UTC)
    for video in videos:
        # Pretend SponsorBlock was asked already, so the demo never calls out.
        video.sponsorblock_fetched_at = now
    db.query(SponsorSegment).delete()
    for index, segments in {
        1: [("sponsor", 0.15, 25)],
        4: [("intro", 0.0, 12), ("sponsor", 0.5, 30)],
        7: [("selfpromo", 0.8, 20)],
    }.items():
        video = videos[index]
        for n, (category, share, length) in enumerate(segments):
            start = round((video.duration_s or 0) * share, 1)
            db.add(SponsorSegment(
                video_id=video.id, uuid=f"demo-{index}-{n}", category=category,
                action="skip", start_s=start, end_s=start + length,
            ))  # fmt: skip
    app_settings = load_app_settings(db)
    app_settings.downloads.sponsorblock_mode = "skip"
    save_app_settings(db, app_settings)

    # A month of finished downloads for the statistics in Verwaltung.
    db.query(DownloadJob).filter(DownloadJob.url.like("%demo-history%")).delete()
    rng = random.Random(3)
    for day in range(30):
        for n in range(rng.choice([0, 0, 1, 1, 2, 3, 5])):
            video = rng.choice(videos)
            finished = now - timedelta(days=day, hours=rng.randint(0, 20), minutes=n)
            db.add(DownloadJob(
                url=f"https://www.youtube.com/watch?v={video.youtube_id}#demo-history",
                youtube_id=video.youtube_id, video_id=video.id,
                status=JobStatus.FAILED if rng.random() < 0.08 else JobStatus.COMPLETED,
                progress=1.0, attempts=1, created_at=finished - timedelta(minutes=3),
                started_at=finished - timedelta(minutes=2), finished_at=finished,
            ))  # fmt: skip

    user = db.query(User).filter_by(is_admin=True).order_by(User.id).first()
    if user is None:
        db.commit()
        print("– Kein Benutzer: Fortschritt und Playlists übersprungen")
        return
    db.query(WatchProgress).filter_by(user_id=user.id).delete()
    for index, share in {1: 0.45, 4: 0.7, 8: 0.25, 2: 1.0, 5: 1.0}.items():
        video = videos[index]
        db.add(WatchProgress(
            user_id=user.id, video_id=video.id, position_s=(video.duration_s or 0) * share,
            watched=share >= 1.0, watched_at=now if share >= 1.0 else None,
            updated_at=now - timedelta(hours=index),
        ))  # fmt: skip
    db.query(Playlist).filter_by(user_id=user.id).delete()
    for name, indexes in [
        ("Entspannen am Abend", [0, 3, 6, 9]),
        ("Technik-Projekte", [4, 10, 1, 7]),
    ]:
        playlist = Playlist(user_id=user.id, name=name)
        playlist.items = [
            PlaylistItem(video_id=videos[i].id, position=pos) for pos, i in enumerate(indexes)
        ]
        db.add(playlist)
    db.commit()
    print(f"✓ Fortschritt und Playlists für {user.username}")


if __name__ == "__main__":
    main()
